#!/bin/sh

FILE_NAME=$(basename $@ | sed -e's/%\([0-9A-F][0-9A-F]\)/\\\\\x\1/g' | xargs echo -e | sed 's/[^[:alnum:]_-]/\\&/g')

DOWNLOAD_PATH=$(grep "downloadPath" .var/app/io.webtorrent.WebTorrent/config/WebTorrent/config.json | cut -d '"' -f 4)

FILE=$(find $DOWNLOAD_PATH -name "$FILE_NAME" -type f)

xdg-open "$FILE"

